# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"

install:
  - npm install

# http://docs.travis-ci.com/user/pull-requests/
script:
  - CITY='Heraklion' node index.js --yes https://www.accuweather.com/en/europe-weather
  - CITY='Budva' node index.js --yes https://www.accuweather.com/en/europe-weather pdf
  - CITY='Paphos' node index.js --yes https://www.accuweather.com/en/europe-weather png
  - CITY='Amsterdam' node index.js --yes https://www.accuweather.com/en/europe-weather pdf
  - node index.js --yes https://www.accuweather.com/en/europe-weather png
  - ls -lah
