# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

install:
  - npm install

before_script:
  - npm run lint

# http://docs.travis-ci.com/user/pull-requests/
script:
  - CITY='Larnaca' node index.js --yes https://www.accuweather.com/en/europe-weather
  - CITY='Marmaris' node index.js --yes https://www.accuweather.com/en/europe-weather pdf
  - node index.js --yes https://www.accuweather.com/en/europe-weather png
  - ls -lah
